CONSUMER_KEY: 'Your Twitter CONSUMER KEY here'
CONSUMER_SECRET: 'Your Twitter CONSUMER_SECRET here'
ACCESS_TOKEN: 'Your Twitter ACCESS_TOKEN here'
ACCESS_TOKEN_SECRET: 'Your Twitter ACCESS_TOKEN_SECRET here'
